### ISSUE TITLE
Implementing a way to freeze/stop the timer

### ISSUE THREAD

**Issue by rpxs** [bradgarropy/use-countdown#12]
I was wondering if it's possible to implement a freeze/stop for the timer. My use case is building a chess timer, and I need to be able to freeze the timer for each side when someone makes a move.

**Comment by bradgarropy** [comment]
Great use case! I'll add this feature in an upcoming release.

**Comment by sleepyArpan** [comment]
Hey @bradgarropy , if you dont mind I would like to give this feature a shot. I think I have a fair idea of what to do here :D

**Comment by bradgarropy** [comment]
Go for it @sleepyArpan!

**Comment by rpxs** [comment]
Any updates on this?

**Comment by bradgarropy** [comment]
@rpxs I'm starting work on this tonight!

**Comment by bradgarropy** [comment]
@rpxs this [pull request](https://github.com/bradgarropy/use-countdown/pull/13) should take care of it!

**Comment by bradgarropy** [comment]
@all-contributors please add @rpxs for ideas

**Comment by bradgarropy** [comment]
Closed by #13. Released in [`v1.3.0`](https://github.com/bradgarropy/use-countdown/releases/tag/v1.3.0).

**Comment by bradgarropy** [comment]
@all-contributors add @rpxs for user testing
