### ISSUE TITLE
Implementing a reset countdown feature

### ISSUE THREAD

**Issue by mehdmhd** [bradgarropy/use-countdown#15]
I want to have the possibility to reset the countdown when a button is clicked. I think it could be relevant to restart the countdown without re-rendering the component.

**Comment by bradgarropy** [comment]
That's a great idea!

In your opinion, do you think the countdown should have to be stopped first? Or could it be reset while running?

Also, if you have any details on your use case (_why_ you need the reset feature) it would help give me some context while implementing it.

**Comment by mehdmhd** [comment]
I think the countdown should be paused or completed before it can be reset.

In my case, I show a button once it has finished, and then reset it (and restart it) when I click on the button.

I use the countdown to specify an expiration in the next few minutes. The button is used to regenerate a code.

**Comment by bradgarropy** [comment]
Thanks, this is great info! I'll start coding the feature tonight live on my [Twitch channel](https://twitch.tv/bradgarropy).

**Comment by bradgarropy** [comment]
@Mehdmhd on reset, would you like the countdown to continue running? Or reset to a paused state?

Currently there is no `start` method. The countdown begins running as soon as it's rendered.

**Comment by mehdmhd** [comment]
In my situation, I'll like to reset also starts the countdown. If I need to stop the countdown, the function `pause` is available. 

If the user calls the `pause` function before the `reset` function,  he should call  the `resume` function to start the countdown. It makes sense for me.

**Comment by bradgarropy** [comment]
Closed with #16.

**Comment by bradgarropy** [comment]
@all-contributors add @Mehdmhd for ideas and user testing
