### ISSUE TITLE
Add a new feature: allow changing the duration of the countdown

### ISSUE THREAD

**Issue by SirIsaacNeutron** [bradgarropy/use-countdown#20]
Hello,

I was just wondering if it would be possible to add an ability to change the countdown duration times after `useCountdown()` has been called.

For example, if you call `reset()`, the countdown will restart but _**always**_ for the duration of time specified on the initial `useCountdown()` call (e.g., 5 seconds). The ability to change the duration of time on a `reset()` would help me significantly with a project I'm working on.

Thank you for reading this,
SirIsaacNeutron

**Comment by bradgarropy** [comment]
This is a great suggestion! Working on it in the [change-duration](https://github.com/bradgarropy/use-countdown/tree/change-duration) branch.

**Comment by bradgarropy** [comment]
I've got a pull request up (#21) with the changes!

@SirIsaacNeutron, can you give it a test drive and let me know if it suits your needs?

**Comment by SirIsaacNeutron** [comment]
Hi @bradgarropy ,

It seems to work perfectly :) thank you for making the change

**Comment by bradgarropy** [comment]
@all-contributors please add @SirIsaacNeutron for bug, ideas, and userTesting

**Comment by bradgarropy** [comment]
@SirIsaacNeutron Released on npm as [v1.5.0](https://www.npmjs.com/package/@bradgarropy/use-countdown), thanks for suggesting the idea!
