### ISSUE TITLE
calling reset() with a time value is causing an error in Next.js (v12)

### ISSUE THREAD

**Issue by ndimatteo** [bradgarropy/use-countdown#25]
Hey there @bradgarropy 🤘  First of all, thanks so much for putting this together, it's been lovely to use!

Unfortunately, I just tested out resetting the timer with a specific time object and it keeps throwing this error: `RangeError: Invalid time value`

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/737188/202271553-f4e98ac6-037f-4e90-b73c-b13f4eddf421.png">

What's confusing is that the error is targeting the hook line, even though I'm making the `reset()` call in another place entirely, via:

```js
resendCodeCountdown.reset({ seconds: 30, format: "s 'sec'" })
```

Additionally here are some details on the versions I'm running this on:
```
@bradgarropy/use-countdown@1.5.1
next@12.3.3
react@18.2.0
```

Any ideas why this might not be working as expected? Thanks so much!

**Comment by ndimatteo** [comment]
Spoke too soon! Looks like if you omit the `minutes` property during a `reset` that causes it.

I think this should probably be allowed, considering it works during the initial hook render, happy to take a stab at a PR for that when I have the time

**Comment by bradgarropy** [comment]
Thanks for filing an issue @ndimatteo!

I think you're seeing an error because of the value you are passing to `reset`. Reset accepts a `Time` input that looks like this:

```typescript
type Time = {
    minutes: number
    seconds: number
}
```

So in your case you should not pass in the `format` property. It would look something like this:

```typescript
resendCodeCountdown.reset({ seconds: 30 })
```

**Comment by bradgarropy** [comment]
Jut saw your last comment! Right, the `Time` type expects both `minutes` and `seconds`. I should totally make that compatible with what's passed into the hook at the beginning.

Could you open an issue to start with? And if you want to submit the pull request that would be 💯

**Comment by bradgarropy** [comment]
@all-contributors please add @ndimatteo for bug
