### ISSUE TITLE
"Cannot find module: 'tslib'"

### ISSUE THREAD

**Issue by narthur** [bradgarropy/use-countdown#28]
I'm trying to use this in my Vite + TypeScript + React project. I'm getting this error:

> Error: Cannot find module 'tslib'
Require stack:
> - /Users/work/ProgrammingProjects/focusqueue/node_modules/.pnpm/@bradgarropy+use-countdown@1.5.2_react@18.2.0/node_modules/@bradgarropy/use-countdown/dist/index.js
 ❯ Object.<anonymous> node_modules/.pnpm/@bradgarropy+use-countdown@1.5.2_react@18.2.0/node_modules/@bradgarropy/use-countdown/dist/index.js:3:15

I found the reference to `tslib` in the compiled dist:

```
"use strict";
exports.__esModule = true;
var tslib_1 = require("tslib");
var countdown_1 = tslib_1.__importDefault(require("./countdown"));
exports["default"] = countdown_1["default"];
tslib_1.__exportStar(require("./types"), exports);
//# sourceMappingURL=index.js.map
```

Looking in `package.json` in this repo, it appears that `tslib` is a dev dependency.

Should that be moved to the regular dependencies list, or should the build step be modified somehow to remove the reference to `tslib` from the compiled distribution?

**Comment by bradgarropy** [comment]
Woah, good find! I have `importHelpers` set to `true` in `tsconfig.json` but I still had `tslib` in the `devDependencies`.

The weird thing is that I can't reproduce this issue. I tried `npx create-next-app@latest` and was able to run `useCountdown` with no issues. What are you using to build your site? Do you have a reproduction or GitHub repository I could look at?

**Comment by msopacua** [comment]
Can we re-open this?
The reason this error occurs with vite [is formulated here](https://github.com/angular/angular-cli/issues/13886#issuecomment-471927518).

Reproduce:
```shell
npm create vite@latest tslib-bug -- --template react-swc-ts
cd tslib-bug
npm install
npm add @bradgarropy/use-countdown
# edit src/App.tsx to import and use use-countdown
npm dev
```

Result:
  ➜  press h to show help
✘ [ERROR] Could not resolve "tslib"

    node_modules/@bradgarropy/use-countdown/dist/index.js:3:22:
      3 │ var tslib_1 = require("tslib");
        ╵                       ~~~~~~~

**Comment by bradgarropy** [comment]
Thank you for the reproduction @msopacua! I was able to successfully reproduce, as well as compare the output bundle sizes with and without `tslib`. As expected, the bundle is smaller with `tslib`.


**Without `tslib`**
package size:  7.4 kB                                  
unpacked size: 25.5 kB    

**With `tslib`**
package size:  7.2 kB                                  
unpacked size: 24.7 kB

**Comment by bradgarropy** [comment]
@all-contributors please add @narthur for bug

**Comment by bradgarropy** [comment]
@all-contributors please add @msopacua for bug

**Comment by bradgarropy** [comment]
@all-contributors please add @msopacua for code
