### ISSUE TITLE
Is there a way to start with the countdown paused?

### ISSUE THREAD

**Issue by JLongley** [bradgarropy/use-countdown#29]
I have a play/pause button in my app that triggers the countdown, but I'd like the default behavior to be for the countdown to be paused until the user hits play.

**Comment by bradgarropy** [comment]
This is a great suggestion @JLongley! I'll try to get to it next week.

**Comment by nfplay** [comment]
Yeap this would be cool! :)

**Comment by bradgarropy** [comment]
We can solve this in two ways. One is a **major** change (breaking), and the other is a **minor** change. Let me know which y'all prefer.

### Major
Modify the `useCountdown()` hook to load in a `paused` state. This would possibly break existing applications and would cause me to bump the package to `v2.0.0`.

### Minor
Include an `autoStart` parameter that defaults to `true`. You could then call it like this to get it to load in a `paused` state.
```
    const countdown = useCountdown({
        minutes: 1,
        seconds: 30,
        format: "mm:ss",
        autoStart: false,
    })
```

Which do you prefer @JLongley / @nfplay?

**Comment by bradgarropy** [comment]
After further consideration, I think I am going to implement both of these suggestions.

- Load the `useCountdown()` hook in a `paused` state.
- Add an `autoStart` property that defaults to `false`.
- Bump the version to `v2.0.0`.

**Comment by bradgarropy** [comment]
Released in `v2.0.0`!

**Comment by bradgarropy** [comment]
@all-contributors please add @JLongley for ideas

**Comment by bradgarropy** [comment]
@all-contributors please add @nfplay for ideas
