### ISSUE TITLE
Countdown overtime

### ISSUE THREAD

**Issue by GoodluckH** [bradgarropy/use-countdown#37]
Hi, 

Is there anyway to allow the timer keep going even after reaching 0?

So, when the timer hits 0, it starts counting up.

**Comment by bradgarropy** [comment]
That's functionality that I would prefer not to implement in this hook.

However, this is a perfect use case for a custom hook to handle this logic. You could leverage the `onCompleted` function to kick off a different timer that counts up when the first one finishes.

I appreciate your willingness to open up this issue, but I think I'm going to close as "won't do".
